In [6]:
import numpy as np

In [7]:
a = np.zeros(5)

In [8]:
a

array([0., 0., 0., 0., 0.])

In [10]:
type(a)

numpy.ndarray

In [11]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [12]:
a.max()

0.0

### Numpy 배열을 만들어보자!

In [13]:
a = np.array( [1, 2, 3, 4, 5])

In [14]:
a

array([1, 2, 3, 4, 5])

In [15]:
type(a)

numpy.ndarray

In [16]:
a = np.array( [ [1,2,3],[4,5,6]  ])

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
b = [ 1, '윤종희', True]

In [19]:
b

[1, '윤종희', True]

In [20]:
type(b[0])

int

In [21]:
type(b[1])

str

In [22]:
type(b[2])

bool

In [23]:
a = np.array(b)

In [24]:
a

array(['1', '윤종희', 'True'], dtype='<U11')

In [25]:
type(a)

numpy.ndarray

In [26]:
type(a[0])

numpy.str_

In [27]:
type(a[1])

numpy.str_

In [28]:
type(a[2])

numpy.str_

## np.zeros

In [29]:
a = np.zeros((3,5))

In [30]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
a = np.zeros((3,5,2))

In [32]:
a

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

## np.eye

In [33]:
a = np.eye(5)

In [34]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
a = np.eye(5, k=-2)

In [43]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

## np.identity

In [36]:
a = np.identity(3)

In [37]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## np.ones

In [44]:
a = np.ones(10)

In [45]:
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
a = np.ones((5,5))

In [47]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
a = np.ones((4,4)) * 5

In [49]:
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [50]:
b = [1,1,1]

In [51]:
b * 5

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [52]:
a = np.ones(3)

In [53]:
a

array([1., 1., 1.])

In [54]:
a * 3

array([3., 3., 3.])

## np.full

In [55]:
a = np.full((3,4), 7)

In [56]:
a

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

## np.empty

In [57]:
a = np.empty( (4,5))

In [58]:
a

array([[1.28632200e-311, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [5.30276956e+180, 1.02941932e-071, 6.97666413e-076,
        4.06255159e-086, 3.35710465e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 1.22199495e+165],
       [3.53666399e-057, 6.52080216e-042, 1.74592005e-076,
        8.07741494e-144, 1.50008929e+248]])

## ~~~~_like

In [59]:
a = np.full((3,5), 3)

In [60]:
a

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [61]:
b = np.ones_like(a)

In [62]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [63]:
a + b

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [64]:
b = np.zeros_like(a)

In [65]:
b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [66]:
a * b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [67]:
b = np.zeros( (3,3))

In [68]:
a * b

ValueError: operands could not be broadcast together with shapes (3,5) (3,3) 

## np.linspace
등간격

In [75]:
a = np.linspace(0, 49)

In [76]:
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [77]:
a = np.linspace(0, 100, 2)

In [78]:
a

array([  0., 100.])

In [79]:
a = np.linspace(0, 100, 5)

In [80]:
a

array([  0.,  25.,  50.,  75., 100.])

In [81]:
a  = np.linspace(0,100, 10)

In [82]:
a

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

## np.logspace
로그스케일

In [83]:
a = np.logspace(1, 50, 10)

In [84]:
a

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [85]:
a = np.ones(5)

In [86]:
a

array([1., 1., 1., 1., 1.])

In [87]:
a.dtype

dtype('float64')

In [88]:
a  = np.ones(5 , dtype=np.int8 )

In [89]:
a

array([1, 1, 1, 1, 1], dtype=int8)

In [90]:
a.dtype

dtype('int8')

In [92]:
a = np.array( [1,2,288], dtype=np.int8)

In [93]:
a

array([ 1,  2, 32], dtype=int8)

In [94]:
a.shape

(3,)

In [95]:
a  = np.ones((3,4))

In [96]:
a.shape

(3, 4)

In [97]:
a.ndim

2

In [98]:
a = np.ones( (3,4,4,4))

In [99]:
a

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

      

In [100]:
a.ndim

4

In [101]:
a.size

192

In [102]:
a.shape

(3, 4, 4, 4)

In [103]:
a.dtype

dtype('float64')

In [104]:
a.itemsize

8

In [105]:
a.data

## 파이썬 vs 넘파이 속도 비교

In [108]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [110]:
list(range(5,10))

[5, 6, 7, 8, 9]

In [111]:
list(range(0, 1, 0.1))

TypeError: 'float' object cannot be interpreted as an integer

In [113]:
list( range(0, 10) ) 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [114]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [115]:
list( np.arange(0, 1, 0.1))

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9]

In [116]:
%time np.sum( np.arange(10000))

Wall time: 0 ns


49995000

In [117]:
%time sum( range(10000))

Wall time: 0 ns


49995000

In [118]:
%time np.sum( np.arange(10000000))

Wall time: 21.4 ms


-2014260032

In [119]:
%time sum( range(10000000))

Wall time: 314 ms


49999995000000

In [120]:
%time np.sum( range(10000000))

Wall time: 1.43 s


-2014260032

In [121]:
a  = b = 1

In [122]:
a

1

In [123]:
b

1

In [124]:
b = 2

In [125]:
a

1

In [126]:
b

2

In [127]:
a = b = [1,2]

In [128]:
a

[1, 2]

In [129]:
b

[1, 2]

In [130]:
b[0] = 100

In [131]:
b

[100, 2]

In [132]:
a

[100, 2]

In [133]:
a = [1,2] #mutable

In [134]:
b = a

In [135]:
a[1] = 2000

In [136]:
a

[1, 2000]

In [137]:
b

[1, 2000]

### Copy 
- Shallow Copy (얉은 복사)
- Deep Copy (깊은 복사)

In [138]:
a = [1,2]

In [139]:
b = a.copy()

In [140]:
b[0] = 1000

In [141]:
b

[1000, 2]

In [142]:
a

[1, 2]

In [143]:
a = b = 1

In [144]:
id(a)

140704288448912

In [145]:
id(b)

140704288448912

In [146]:
id(1)

140704288448912

In [147]:
b = 2

In [148]:
id(a)

140704288448912

In [149]:
id(b)

140704288448944

In [150]:
id(2)

140704288448944

In [151]:
a = b = [1,2]

In [152]:
id(a)

2603738955336

In [153]:
id(b)

2603738955336

In [154]:
b[0] = 1000

In [155]:
id(b)

2603738955336

In [156]:
b = [1,2,3]

In [157]:
id(b)

2603755593992

In [158]:
a = [ [1,2,3]]

In [159]:
a

[[1, 2, 3]]

In [160]:
b = a.copy()

In [161]:
b

[[1, 2, 3]]

In [162]:
b[0][0] = 1000

In [163]:
b

[[1000, 2, 3]]

In [164]:
a

[[1000, 2, 3]]

In [165]:
import copy

In [166]:
a = [ [1,2,3]]

In [167]:
b = copy.deepcopy( a )

In [168]:
b

[[1, 2, 3]]

In [169]:
b[0][0] = 1000

In [170]:
b

[[1000, 2, 3]]

In [171]:
a

[[1, 2, 3]]

In [172]:
a = [1,2,3]

In [174]:
a[0:2]

[1, 2]

In [175]:
b = a[:]  # b = a

In [176]:
b[0] = 1000

In [177]:
b

[1000, 2, 3]

In [178]:
a

[1, 2, 3]

In [179]:
a = b = np.array( [1,2,3])

In [180]:
a[0]

1

In [181]:
a[:]

array([1, 2, 3])

In [182]:
a[0] = 1000

In [183]:
a

array([1000,    2,    3])

In [184]:
b

array([1000,    2,    3])

In [185]:
# numpy ndarray --> mutable

In [187]:
a =  np.array( [1,2,3])

In [188]:
b = a.copy()

In [189]:
b[0] =1000

In [190]:
a

array([1, 2, 3])

In [191]:
b

array([1000,    2,    3])

## 값을 가져오는 방법

In [192]:
a = [ [1,2,3] , [4,5,6]]

In [193]:
a

[[1, 2, 3], [4, 5, 6]]

In [194]:
a[0][0]

1

In [195]:
a[1][1]

5

In [196]:
a[0,0]

TypeError: list indices must be integers or slices, not tuple

In [197]:
b = np.array( a)

In [198]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [201]:
b[0][0]

1

In [202]:
b[1][1]

5

In [203]:
b[0,0]

1

In [204]:
b[1,1]

5

### boolean indexing

In [205]:
a = np.array( [1,2,3,4,5])

In [206]:
a > 3

array([False, False, False,  True,  True])

In [207]:
a[ a>3 ]

array([4, 5])

In [210]:
a[ [ True, False, False, True, True] ]

array([1, 4, 5])

In [211]:
### 점심 시간 ###

In [212]:
a  = np.array( [5,2, 1, 6, 7, 10])

In [213]:
b = a[ a<6  ]

In [214]:
b

array([5, 2, 1])

In [215]:
a%2 != 0

array([ True, False,  True, False,  True, False])

In [216]:
a%2 == 1

array([ True, False,  True, False,  True, False])

In [217]:
b = a[ a%2 == 1 ]

In [218]:
b

array([5, 1, 7])

In [219]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [220]:
a = np.array( [1,2,3,4,5,6])

In [221]:
a

array([1, 2, 3, 4, 5, 6])

In [222]:
a.shape

(6,)

In [223]:
a.ndim

1

In [224]:
a.reshape( (2,3) )

array([[1, 2, 3],
       [4, 5, 6]])

In [225]:
a.reshape( (3,2) )

array([[1, 2],
       [3, 4],
       [5, 6]])

In [226]:
a.reshape( (4,2) )

ValueError: cannot reshape array of size 6 into shape (4,2)

In [227]:
a.reshape( (2,2))

ValueError: cannot reshape array of size 6 into shape (2,2)

In [228]:
b = np.arange(100).reshape( (20,5) )

In [229]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

## fancy indexing

In [230]:
b[0,0]

0

In [231]:
b[ [6, 8, 10] ] #6행, 8행, 10행

array([[30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [50, 51, 52, 53, 54]])

In [232]:
b[ [6:11:2] ] #slicing을 사용할 수는 없다.

SyntaxError: invalid syntax (<ipython-input-232-2a9fc4b37988>, line 1)

In [233]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [234]:
c = b[ [0,1,2]]

In [235]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [236]:
c[0,0] = 1000

In [237]:
c

array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14]])

In [238]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [239]:
b[ [0,1,2] , [0,1,2]]

array([ 0,  6, 12])

In [241]:
b[ [0,1,2,5] , [0,1,2,10]]

IndexError: index 10 is out of bounds for axis 1 with size 5

## 3차원 데이터

In [242]:
b = np.arange(24).reshape( (2,3,4) )

In [243]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [244]:
b.ndim

3

In [245]:
b[ 0 ]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [246]:
b[0].ndim

2

In [247]:
b[ [0] ] #fancy indexing -> 차원이 같은 형태로 부분 배열을 선택한다.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [248]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [249]:
b[0, :, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [250]:
b[0, ... ]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [251]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [252]:
b[0, : , 1 ]

array([1, 5, 9])

13,17,21, 15, 19 , 23

In [253]:
b[1, :, [1, 3] ]

array([[13, 17, 21],
       [15, 19, 23]])

In [254]:
b[1, :, 1::2]

array([[13, 15],
       [17, 19],
       [21, 23]])

### 연산

In [255]:
a = np.arange(12).reshape((3,4))

In [257]:
b = np.arange(12, 24).reshape( (3,4))

In [258]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [259]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# vectorize 연산
--> elementwise 연산

In [260]:
a + b

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [261]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [262]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [263]:
[1,2,3] + [10,20,30]

[1, 2, 3, 10, 20, 30]

In [264]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [265]:
a @ b  # matrix dot operation,행렬곱

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [266]:
a.shape

(3, 4)

In [267]:
b.shape

(3, 4)

In [268]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [269]:
b.T #전치행렬

array([[12, 16, 20],
       [13, 17, 21],
       [14, 18, 22],
       [15, 19, 23]])

In [270]:
a @ b.T

array([[ 86, 110, 134],
       [302, 390, 478],
       [518, 670, 822]])

In [271]:
e = np.matrix( [ [1,2], [3,4]])

In [272]:
type(e)

numpy.matrix

In [273]:
e * e # matrix dot operation

matrix([[ 7, 10],
        [15, 22]])

In [274]:
e

matrix([[1, 2],
        [3, 4]])

## broadcasting

In [275]:
[1, 2, 3] + 5

TypeError: can only concatenate list (not "int") to list

In [276]:
a = np.arange(12).reshape( (3, 4) )

In [277]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [278]:
a + 5

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [279]:
np.full( (3,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [280]:
b = np.array( [10,20,30,40])

In [281]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [282]:
b

array([10, 20, 30, 40])

In [283]:
a + b

array([[10, 21, 32, 43],
       [14, 25, 36, 47],
       [18, 29, 40, 51]])

In [284]:
c = np.array([1,2,3])

In [285]:
a + c

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [286]:
d = np.array( [1,2])

In [287]:
a + d

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

## 축, axis

In [288]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [289]:
np.sum(a)

66

In [290]:
np.sum(a, axis = 0) #행방향

array([12, 15, 18, 21])

In [291]:
np.sum(a, axis = 1) #열방향

array([ 6, 22, 38])

In [292]:
a.shape

(3, 4)

In [293]:
np.sum(a, axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [294]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [295]:
np.max(a)

11

In [296]:
np.max(a, axis =0)

array([ 8,  9, 10, 11])

In [297]:
np.max(a, axis=1)

array([ 3,  7, 11])

In [298]:
a = np.arange(24).reshape(2,3,4)

In [299]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [300]:
a.shape

(2, 3, 4)

2차원 : (행, 열)
3차원 : (공간, 행, 열)
    

In [301]:
np.max(a)

23

In [302]:
np.max(a, axis=0)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [303]:
np.sum(a, axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [304]:
np.sum(a, axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

## universial function
--> ufunc

In [305]:
type( np.max )

function

In [306]:
type( np.add )

numpy.ufunc

In [307]:
type( add )

NameError: name 'add' is not defined

In [308]:
from operator import add

In [309]:
type(add)

builtin_function_or_method

In [310]:
add( 1, 3)

4

In [311]:
np.add( 1, 3)

4

In [312]:
add( [1,2,3] , [4,5,6])

[1, 2, 3, 4, 5, 6]

In [313]:
np.add( [1,2,3], [4,5,6])

array([5, 7, 9])

In [314]:
a = np.array( [10,1, 2,3,30, -1, 1023])

In [315]:
a

array([  10,    1,    2,    3,   30,   -1, 1023])

In [316]:
np.max(a)

1023

In [317]:
np.min(a)

-1

In [318]:
np.argmax(a)

6

In [320]:
np.argmin(a)

5

In [321]:
a = np.arange(24).reshape( 3,8 ) #tuple auto packing

In [322]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [323]:
a = np.arange(24).reshape( (3,8) )

In [324]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [325]:
a, b, c = 1, 2, 3

In [326]:
a

1

In [327]:
a = np.arange(24).reshape( (3,8) )

In [328]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [329]:
a.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [330]:
a.reshape( 2, -1 )

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [331]:
a.reshape( -1, 6 )

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [332]:
a.reshape ( 5, -1)

ValueError: cannot reshape array of size 24 into shape (5,newaxis)

In [333]:
a.reshape( -1, -1 )

ValueError: can only specify one unknown dimension

In [334]:
a.reshape()

TypeError: reshape() takes exactly 1 argument (0 given)

## resize

In [335]:
a = np.arange(24)

In [336]:
a.size

24

In [337]:
a.resize( (2, 3) )

In [338]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [339]:
a.size

6

In [342]:
a = np.arange(24)

In [343]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [345]:
a.resize( 2,3,8)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [346]:
np.resize(a, (2,3,8) )

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]],

       [[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]]])

In [347]:
np.resize(a, (6,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [348]:
a = np.arange(100).reshape(10, -1)

In [349]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [350]:
np.savetxt('savedata.csv', a, delimiter=',', fmt ='%d') #넘파이 객체 -> 파일로 저장

In [351]:
b = np.loadtxt('savedata.csv', delimiter=',', dtype=np.int)

In [352]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [355]:
temp_data = np.loadtxt('daegu_20210712.csv', delimiter=',', skiprows=8 )

ValueError: could not convert string to float: '2011-06-12'

In [354]:
temp_data

array([[80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
       [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])

In [361]:
def genNewTempDataFile():
    dataFileName = 'daegu_20210712.csv'
    newFileName = 'new_daegu_20210712.csv'
    
    read_f = open(dataFileName, 'r')
    write_f = open(newFileName, 'w')
    
    while True:
        line = read_f.readline() #파일에서 한 줄 읽어오기
        if not line:
            break;
        
        splitData = line.split(',')
        
        skipWriting = False
        
        if len(splitData) == 5 and splitData[1].isnumeric() :
            splitData[0] = splitData[0].replace('-','')
            
            for data in splitData:
                try:
                    float(data)
                except ValueError:
                    print("에러 : ", splitData[0])
                    skipWriting = True
                    break
                    
            if not skipWriting:
                newData = ','.join(splitData)
                write_f.write(newData)
    
    write_f.close()
    read_f.close()
            

In [362]:
genNewTempDataFile()

에러 :  20130930
에러 :  20170729
에러 :  20210710


In [363]:
temp_data = np.loadtxt('new_daegu_20210712.csv', delimiter=',')

temp_data.shape

In [364]:
temp_data.shape

(3680, 5)

## 최고 온도 구하기

In [365]:
np.max(temp_data)

20210711.0

In [366]:
temp_data

array([[2.0110612e+07, 1.4300000e+02, 2.4600000e+01, 2.0800000e+01,
        2.9700000e+01],
       [2.0110613e+07, 1.4300000e+02, 2.3700000e+01, 1.9600000e+01,
        2.9400000e+01],
       [2.0110614e+07, 1.4300000e+02, 2.4100000e+01, 1.9200000e+01,
        2.9400000e+01],
       ...,
       [2.0210708e+07, 1.4300000e+02, 2.4900000e+01, 2.2500000e+01,
        2.9600000e+01],
       [2.0210709e+07, 1.4300000e+02, 2.4700000e+01, 2.2100000e+01,
        2.9100000e+01],
       [2.0210711e+07, 1.4300000e+02, 2.5700000e+01, 2.1100000e+01,
        3.3800000e+01]])

In [367]:
temp_data[ : , 4]

array([29.7, 29.4, 29.4, ..., 29.6, 29.1, 33.8])

In [368]:
np.max( temp_data[ :, 4])

39.2

In [369]:
np.argmax( temp_data[ :, 4])

2600

In [370]:
temp_data[ 2600 , 0]

20180727.0

## 최저 기온

In [372]:
np.min( temp_data[:, 3])

-13.9

In [373]:
np.argmin( temp_data[:,3])

2419

In [374]:
temp_data[2419, 0]

20180127.0

In [375]:
np.max( temp_data, axis = 0)

array([2.0210711e+07, 1.4300000e+02, 3.3100000e+01, 2.8600000e+01,
       3.9200000e+01])

In [376]:
np.max( temp_data, axis = 0)[4]

39.2

In [377]:
np.argmax( temp_data, axis=0)

array([3679,    0, 2599, 2600, 2600], dtype=int64)

In [378]:
np.argmax( temp_data, axis=0)[4]

2600

In [379]:
np.min( temp_data, axis=0)[3]

-13.9

In [380]:
np.argmin( temp_data, axis=0)[3]

2419

In [382]:
temp_data[ np.argmin( temp_data, axis=0)[3] , 0 ].astype(np.int)

20180127

## 최고 기온, 최저 기온 Top 10 날짜와 기온을 구하시오.

np.delete 행삭제...

예제)
temp_data = np.delete(temp_data, 2600, axis=0) 